sudo: required
services:
- docker
before_install:
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- openssl aes-256-cbc -K $encrypted_e2b3672fe6bc_key -iv $encrypted_e2b3672fe6bc_iv
  -in deploy_key.enc -out deploy_key -d
- docker build -t $DOCKER_HUB_USERNAME/docker-react:dev -f Dockerfile.dev .
- docker build -t $DOCKER_HUB_USERNAME/docker-react:production -f Dockerfile .
script:
- docker run -e CI=true pavelsab/docker-react:dev npm run test -- --coverage
- docker push $DOCKER_HUB_USERNAME/docker-react:production
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push
  script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key root@140.82.32.21 './deploy.sh'
  on:
    branch: master
env:
  global:
  - secure: YAuG4+EhIqDzV7/L3/lN0aOmgZ+BF7UR+5uuwc00RA/KYcUg36M+PNuw1LM6wKPmXGWIkm7aLQU0VZKA2ZkEUJQBA1fGyZVVRnXocLMTdIhCYScqcbtl5uvL1Fnm2d8HxCL+FE9SFLn8As5/g4Jjgv8ZTZR7awpgKwxFdYfE0aUY9PNKrePFZSGtZ++GuXUnGLIG/Nx3IbiQJftyaMsvWmK2OH5xiEYFlI5KmW76zztsf1y0m7NepQXMgjFlB2vvNFOjZnkdrF1TlaPXHk0FRwBQzKZ1F6wRlOQ843tjMNR3ep9iHICxKFzFH/mPszMcmKLNZmgJkiOhan71ieeKkcqSdLt1i95xqO4zBncBsTp3Hxyjl2q7mRsonIFHwqcpTXjfAWVSsykG9xT6Mtc3fDkkqecZe0pgWDYx47OGY2biZSbvMk44BVSNM7LK9xGtpw1q0CxKYVgyiKLSIXNU8N3viFUC6qJCSHPYgY9apAsrsEaNGgBroi/egwsJ9GqlhTNH/T86MDuGCtEmhwwmCx3QXjOVNkWc7YldMShbHZ7xzywdbvSxRh5Q3kdv0KPT13C/GmObJxhKeHrGyczDpAbcY+1irv2y62PpbCnoXODviU5ICAuGh3hpd9DqfbVmAYckUlcatcVjSCQ+SFqtpuYdvYUA8jKRC7yBevrf8Fo=
  - secure: NUtMDYffXEgZvwKz97l5Aoq2wuQ19pabaTjnOvu5p+T3EqkyADzHRJclT5qct6eEE31tpjfMxEdboZawS/zG/8IqG5x9NXIgBWEJ0mpCOBu5kbCFh0Ja+KYLU1D6Hj54odQKZ5k5PMNFxcVKPyuMyPr6VrG8mJp293d7pJVHrmpSX0dFBMvu/Qn7JzrY4RNuJpW2A2GpRFHkELoU4C9ONSr78VwHIwSzUpCraWoz++0rN8ke6ErBUUDUwQrtIx20/3eChBck6WAVkyjW2iBsJqeWAhhi75R5iEYrG3FvlAdeOWWWrrdFSJO9QsHU0/f+C+qRp/hREUNz7z3FvYOIWBDh5Rw0gzxD0BSEH8H18a53VO8WWa3H0IE2y8+3IuKKN2nEhcgFVf6FDZqdPduG67EKr9ce1v+Z332Z6t2ntd3DcCFIDxhvHGXsvRe1BOxBTqXJhUKY70ygO9ZBbnGIyTHNor/hIQQQOzGk1kKkb+vYUMZG5IFYWyF1SPRA1+86KaOBNLd5vHk824a2we3p1+lmCdeUG1igz9Bx9xHmq+Ta+wygEG4wEbkAM0DDCX4iEe9zrgH0fiTiw4pDPylu4a5QxTKx4KXjzXLNBRFOC2ArZyPV7o24W8kD4SCw8vdMYY6dXsgkeUsiDOvJ9IuQtzVPwaDQmULyEo9zxJedOW0=
  - secure: vvjdvdeQ0iZSl7DkilZYQxwJCAY2RmxYEqp1uF999os4PJwXyJ01h00UDvBrTu5nRYhy2H8akRCbTVPH1VIqSsap//StdWrRBZ8kY737YXICzFmyr+Q4sJZVFg0Lkzf6Zenly3PrVQ7iMqWK5mZ/PDdguAuxkaI2FVZn/j8HTDqG+M8dImuqHyKUsUPctrTb4j4VZ8nkjXqXRvnkG9+bsJXq0OCBZ5NqziaSPHWBgQR0/MiKFUlH9IGVaWOYMtr9sLfweW0iuS/x9Xe81GNJ1T5KIVbBzXqbKzoic8zvDyN+1GfJOHAPLsI3Gybju3ms89j8AB9DjilObJSZXYGSzBeV70G6bjZXsm+KZf5JNZkNpBZt8zWJy/P7iG/KCMsi5N8Wkx5SIvP2qxqIEOJuox+DTYU14qN+MBQ2BPrPnAHxho9EVKBDzKElKXrlHbyQUr07zpMzknJxJww+d/wSWgBFciJDweSTou75N6D3HvtIS8JEsPzULZ+NDhy1JHiOMo9rOw3C5AtKGIGxhj0Nu/8y9PwsJgfkGOYEM19DQ29VwPqHUxDddhhTyx/aP4AJAIYaMxSy8YIlKfazTcKJXWeEaaCZ26oDMycKkF2o6lqvyum83t2Ro8/F7yURUAn0OVmnhox4Z8SBnWZud0rMOIgD5M3V7/DIDfJCk579w0E=
