sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e2b3672fe6bc_key -iv $encrypted_e2b3672fe6bc_iv
  -in deploy_key.enc -out deploy_key -d
- docker build -t pavelsab/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true pavelsab/docker-react npm run test -- --coverage
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
